version: '2'
services:
    auth-app:
        image: auth
        external_links:
            - auth-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/auth
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    auth-postgresql:
        extends:
            file: postgresql.yml
            service: auth-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
